// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:3e21c29d-b943-4e5b-958c-f97045d985c3",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_nUIx2IcbG",
    "aws_user_pools_web_client_id": "4oc7ira3g8fdhiq60j2ae1su8b",
    "aws_mobile_analytics_app_id": "d4667c199c0646a290f57583072de363",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
